package com.example.ecommercefoodappcompose.ui.theme
import androidx.compose.ui.graphics.Color

// @Composable
// fun themedColor(vararg variants: Pair<AppTheme, Color>): Color {
//    val themeState = LocalThemeState.current
//    return variants.toMap()[themeState.currentAppTheme] ?: Color.Black
// }

// val inversePrimaryDark: Color
//    @Composable get() = themedColor(
//        AppTheme.GREEN to Color(0xFF36693E),
//        AppTheme.RED to Color.Red,
//    )

val primaryLightGreen = Color(0xFF36693E)
val onPrimaryLightGreen = Color(0xFFFFFFFF)
val primaryContainerLightGreen = Color(0xFFB7F1B9)
val onPrimaryContainerLightGreen = Color(0xFF002108)
val secondaryLightGreen = Color(0xFF516351)
val onSecondaryLightGreen = Color(0xFFFFFFFF)
val secondaryContainerLightGreen = Color(0xFFD4E8D1)
val onSecondaryContainerLightGreen = Color(0xFF0F1F11)
val tertiaryLightGreen = Color(0xFF39656C)
val onTertiaryLightGreen = Color(0xFFFFFFFF)
val tertiaryContainerLightGreen = Color(0xFFBDEAF3)
val onTertiaryContainerLightGreen = Color(0xFF001F24)
val errorLightGreen = Color(0xFFBA1A1A)
val onErrorLightGreen = Color(0xFFFFFFFF)
val errorContainerLightGreen = Color(0xFFFFDAD6)
val onErrorContainerLightGreen = Color(0xFF410002)
val backgroundLightGreen = Color(0xFFF7FBF2)
val onBackgroundLightGreen = Color(0xFF181D18)
val surfaceLightGreen = Color(0xFFF7FBF2)
val onSurfaceLightGreen = Color(0xFF181D18)
val surfaceVariantLightGreen = Color(0xFFDDE5D9)
val onSurfaceVariantLightGreen = Color(0xFF424940)
val outlineLightGreen = Color(0xFF727970)
val outlineVariantLightGreen = Color(0xFFC1C9BE)
val scrimLightGreen = Color(0xFF003210)
val inverseSurfaceLightGreen = Color(0xFF2D322C)
val inverseOnSurfaceLightGreen = Color(0xFFEEF2E9)
val inversePrimaryLightGreen = Color(0xFF36693E)
val surfaceDimLightGreen = Color(0xFFD7DBD3)
val surfaceBrightLightGreen = Color(0xFFF7FBF2)
val surfaceContainerLowestLightGreen = Color(0xFFFFFFFF)
val surfaceContainerLowLightGreen = Color(0xFFF1F5EC)
val surfaceContainerLightGreen = Color(0xFFEBEFE7)
val surfaceContainerHighLightGreen = Color(0xFFE5E9E1)
val surfaceContainerHighestLightGreen = Color(0xFFE0E4DB)

val primaryLightRed = Color(0xFFAF0023)
val onPrimaryLightRed = Color(0xFFFFFFFF)
val primaryContainerLightRed = Color(0xFFDC0930)
val onPrimaryContainerLightRed = Color(0xFFFFEEED)
val secondaryLightRed = Color(0xFFAC3137)
val onSecondaryLightRed = Color(0xFFFFFFFF)
val secondaryContainerLightRed = Color(0xFFFD6D6E)
val onSecondaryContainerLightRed = Color(0xFF6D0012)
val tertiaryLightRed = Color(0xFF854500)
val onTertiaryLightRed = Color(0xFFFFFFFF)
val tertiaryContainerLightRed = Color(0xFFA95900)
val onTertiaryContainerLightRed = Color(0xFFFFEFE5)
val errorLightRed = Color(0xFFBA1A1A)
val onErrorLightRed = Color(0xFFFFFFFF)
val errorContainerLightRed = Color(0xFFFFDAD6)
val onErrorContainerLightRed = Color(0xFF93000A)
val backgroundLightRed = Color(0xFFFFF8F7)
val onBackgroundLightRed = Color(0xFF291716)
val surfaceLightRed = Color(0xFFFFF8F7)
val onSurfaceLightRed = Color(0xFF291716)
val surfaceVariantLightRed = Color(0xFFFFDAD8)
val onSurfaceVariantLightRed = Color(0xFF5D3F3E)
val outlineLightRed = Color(0xFF926E6D)
val outlineVariantLightRed = Color(0xFFE7BCBB)
val scrimLightRed = Color(0xFF000000)
val inverseSurfaceLightRed = Color(0xFF402B2A)
val inverseOnSurfaceLightRed = Color(0xFFFFEDEB)
val inversePrimaryLightRed = Color(0xFFFFB3B0)
val surfaceDimLightRed = Color(0xFFF4D2D1)
val surfaceBrightLightRed = Color(0xFFFFF8F7)
val surfaceContainerLowestLightRed = Color(0xFFFFFFFF)
val surfaceContainerLowLightRed = Color(0xFFFFF0EF)
val surfaceContainerLightRed = Color(0xFFFFE9E7)
val surfaceContainerHighLightRed = Color(0xFFFFE1E0)
val surfaceContainerHighestLightRed = Color(0xFFFDDBD9)

val primaryDarkGreen = Color(0xFF9CD49F)
val onPrimaryDarkGreen = Color(0xFF003913)
val primaryContainerDarkGreen = Color(0xFF1D5128)
val onPrimaryContainerDarkGreen = Color(0xFFB7F1B9)
val secondaryDarkGreen = Color(0xFFB8CCB5)
val onSecondaryDarkGreen = Color(0xFF243425)
val secondaryContainerDarkGreen = Color(0xFF3A4B3A)
val onSecondaryContainerDarkGreen = Color(0xFFD4E8D1)
val tertiaryDarkGreen = Color(0xFFA1CED6)
val onTertiaryDarkGreen = Color(0xFF00363D)
val tertiaryContainerDarkGreen = Color(0xFF1F4D54)
val onTertiaryContainerDarkGreen = Color(0xFFBDEAF3)
val errorDarkGreen = Color(0xFFFFB4AB)
val onErrorDarkGreen = Color(0xFF690005)
val errorContainerDarkGreen = Color(0xFF93000A)
val onErrorContainerDarkGreen = Color(0xFFFFDAD6)
val backgroundDarkGreen = Color(0xFF101510)
val onBackgroundDarkGreen = Color(0xFFE0E4DB)
val surfaceDarkGreen = Color(0xFF101510)
val onSurfaceDarkGreen = Color(0xFFE0E4DB)
val surfaceVariantDarkGreen = Color(0xFF424940)
val onSurfaceVariantDarkGreen = Color(0xFFC1C9BE)
val outlineDarkGreen = Color(0xFF8B9389)
val outlineVariantDarkGreen = Color(0xFF424940)
val scrimDarkGreen = Color(0xFF000000)
val inverseSurfaceDarkGreen = Color(0xFFE0E4DB)
val inverseOnSurfaceDarkGreen = Color(0xFF2D322C)
val inversePrimaryDarkGreen = Color(0xFF36693E)
val surfaceDimDarkGreen = Color(0xFF101510)
val surfaceBrightDarkGreen = Color(0xFF363A35)
val surfaceContainerLowestDarkGreen = Color(0xFF0B0F0B)
val surfaceContainerLowDarkGreen = Color(0xFF181D18)
val surfaceContainerDarkGreen = Color(0xFF1C211C)
val surfaceContainerHighDarkGreen = Color(0xFF272B26)
val surfaceContainerHighestDarkGreen = Color(0xFF313630)

val primaryDarkRed = Color(0xFFFFB3B0)
val onPrimaryDarkRed = Color(0xFF680010)
val primaryContainerDarkRed = Color(0xFFDC0930)
val onPrimaryContainerDarkRed = Color(0xFFFFEEED)
val secondaryDarkRed = Color(0xFFFFB3B0)
val onSecondaryDarkRed = Color(0xFF680010)
val secondaryContainerDarkRed = Color(0xFF8E1A24)
val onSecondaryContainerDarkRed = Color(0xFFFF9E9B)
val tertiaryDarkRed = Color(0xFFFFB780)
val onTertiaryDarkRed = Color(0xFF4E2600)
val tertiaryContainerDarkRed = Color(0xFFA95900)
val onTertiaryContainerDarkRed = Color(0xFFFFEFE5)
val errorDarkRed = Color(0xFFFFB4AB)
val onErrorDarkRed = Color(0xFF690005)
val errorContainerDarkRed = Color(0xFF93000A)
val onErrorContainerDarkRed = Color(0xFFFFDAD6)
val backgroundDarkRed = Color(0xFF1F0F0E)
val onBackgroundDarkRed = Color(0xFFFDDBD9)
val surfaceDarkRed = Color(0xFF1F0F0E)
val onSurfaceDarkRed = Color(0xFFFDDBD9)
val surfaceVariantDarkRed = Color(0xFF5D3F3E)
val onSurfaceVariantDarkRed = Color(0xFFE7BCBB)
val outlineDarkRed = Color(0xFFAD8886)
val outlineVariantDarkRed = Color(0xFF5D3F3E)
val scrimDarkRed = Color(0xFF000000)
val inverseSurfaceDarkRed = Color(0xFFFDDBD9)
val inverseOnSurfaceDarkRed = Color(0xFF402B2A)
val inversePrimaryDarkRed = Color(0xFFBF0027)
val surfaceDimDarkRed = Color(0xFF1F0F0E)
val surfaceBrightDarkRed = Color(0xFF493433)
val surfaceContainerLowestDarkRed = Color(0xFF1A0A09)
val surfaceContainerLowDarkRed = Color(0xFF291716)
val surfaceContainerDarkRed = Color(0xFF2D1B1A)
val surfaceContainerHighDarkRed = Color(0xFF392524)
val surfaceContainerHighestDarkRed = Color(0xFF452F2F)

val inversePrimaryDarkHighContrastGreen = Color(0xFF003210)
val inversePrimaryDarkHighContrastRed = Color(0xFF95001C)
